// Website/src/components/Footer.vue
<template>
	<footer>
		<div class="wrapper">
			<div class="left">
				<div class="copyright">
					{{ year }} &copy; Skia4Delphi. All rights reserved.
				</div>
			</div>
			<div class="right">
				<nav>
					<a
						class="btn github"
						href="https://github.com/viniciusfbb/skia4delphi"
						title="Github"
						target="_blank"
						><span>Github</span></a
					>
				</nav>
			</div>
		</div>
	</footer>
</template>

<script>
	export default {
		data() {
			return {
				year: 0,
			};
		},
		beforeMount() {
			const date = new Date();

			this.year = date.getFullYear();
		},
	};
</script>

<style scoped>
	footer {
		background-color: #000;
		display: flex;
		flex-flow: row nowrap;
		height: 80px;
		width: 100%;
	}

	footer > .wrapper {
		align-items: center;
		display: flex;
		flex-flow: row nowrap;
		height: 100%;
	}

	footer .left {
		flex-grow: 1;
	}

	footer .btn {
		transition: opacity 0.3s;

		background: url("../assets/logo-github.svg");
		display: block;
		height: 28px;
		width: 28px;
	}

	footer .btn:hover {
		opacity: 0.5;
	}

	footer .btn span {
		display: none;
	}

	@media (max-width: 600px) {
		footer {
			height: 60px;
		}

		footer .left {
			font-size: 0.875rem;
			text-align: center;
		}

		footer .right {
			display: none;
		}
	}
</style>

// Website/src/components/organisms/Footer.tsx
import { Container, Row, Col, Text } from '@nextui-org/react';
import {Link} from 'react-router-dom';
import { IoLogoGithub } from 'react-icons/io5';
import styled from '@emotion/styled';

const Footer = styled.footer`
  background-color: #000000;
`;

export default () => (
  <Footer>
    <Container css={{paddingTop: 16}}>
        <Row>
          <Col><Text>{new Date().getUTCFullYear()} © Skia4Delphi. All rights reserved.</Text></Col>
          <Col css={{
            display: 'flex',
            justifyContent: 'end',
            fontSize: 30,
            svg: {color: 'white'}
          }}>
            <a href="https://github.com/viniciusfbb/skia4delphi">
              <IoLogoGithub />
            </a>
          </Col>
        </Row>
    </Container>
  </Footer>
);
